# ============================================================
#  Render Bangla UI strings to PNGs.
#
#  Why this exists: raylib draws glyphs one codepoint at a time
#  with no shaping. Bengali needs reordering (the vowel sign in
#  "ki" is stored after its consonant but drawn before it) and
#  conjuncts. Drawn naively it comes out scrambled. Windows'
#  DirectWrite shapes correctly, so each string is baked to an
#  image once and the game just blits it.
#
#  The Bangla itself lives in tools/bangla_strings.txt, read as
#  UTF-8. It is deliberately NOT in this file: Windows PowerShell
#  5.1 parses .ps1 as ANSI unless it has a BOM, which mangles it.
#
#      powershell -ExecutionPolicy Bypass -File tools/make_bangla.ps1
#
#  Writes assets/text/<id>.png and src/textids.h
# ============================================================
Add-Type -AssemblyName PresentationCore, PresentationFramework, WindowsBase

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$out  = Join-Path $root "assets\text"
New-Item -ItemType Directory -Force -Path $out | Out-Null

$FONT = "Kalpurush"
$culture = [Globalization.CultureInfo]::GetCultureInfo("bn-BD")

# Supersample. The sizes in bangla_strings.txt describe how big the text should
# LOOK in the game; rendering at exactly that size gives Bengali matras and
# dots barely a pixel each, and no amount of scaling afterwards puts detail
# back. Baking 4x larger and letting the GPU scale down keeps them sharp.
$SUPER = 4

$lines = Get-Content (Join-Path $PSScriptRoot "bangla_strings.txt") -Encoding UTF8
$rows = @()
foreach ($ln in $lines) {
    $t = $ln.Trim()
    if ($t -eq "" -or $t.StartsWith("#")) { continue }
    $p = $t -split '\|'
    if ($p.Count -lt 4) { continue }
    $rows += , @($p[0].Trim(), $p[1].Trim(), [int]$p[2].Trim(), $p[3].Trim())
}

function Save-Text($id, $text, $size, $hex) {
    $size = $size * $SUPER
    $tf = New-Object Windows.Media.Typeface($FONT)
    $brush = New-Object Windows.Media.SolidColorBrush(
                [Windows.Media.ColorConverter]::ConvertFromString($hex))
    $shadow = New-Object Windows.Media.SolidColorBrush(
                [Windows.Media.Color]::FromArgb(210, 0, 0, 0))

    $mk = {
        param($b)
        New-Object Windows.Media.FormattedText(
            $text, $culture, [Windows.FlowDirection]::LeftToRight, $tf, $size, $b, 96)
    }
    $ft = & $mk $brush

    $pad = [int][Math]::Ceiling($size * 0.20) + $SUPER * 2
    $w = [int][Math]::Ceiling($ft.Width) + $pad * 2
    $h = [int][Math]::Ceiling($ft.Height) + $pad * 2

    $dv = New-Object Windows.Media.DrawingVisual
    $dc = $dv.RenderOpen()
    # 8-way dark outline, offset by the supersample factor so it stays a
    # roughly one-pixel rim once the image is scaled back down in game
    $o = $SUPER
    foreach ($dx in -$o, 0, $o) {
        foreach ($dy in -$o, 0, $o) {
            if ($dx -eq 0 -and $dy -eq 0) { continue }
            $dc.DrawText((& $mk $shadow),
                (New-Object Windows.Point(($pad + $dx), ($pad + $dy))))
        }
    }
    $dc.DrawText($ft, (New-Object Windows.Point($pad, $pad)))
    $dc.Close()

    $rtb = New-Object Windows.Media.Imaging.RenderTargetBitmap(
            $w, $h, 96, 96, [Windows.Media.PixelFormats]::Pbgra32)
    $rtb.Render($dv)
    $enc = New-Object Windows.Media.Imaging.PngBitmapEncoder
    $enc.Frames.Add([Windows.Media.Imaging.BitmapFrame]::Create($rtb))
    $fs = [IO.File]::Open((Join-Path $out "$id.png"), [IO.FileMode]::Create)
    $enc.Save($fs); $fs.Close()
    return @($w, $h)
}

$hdr = New-Object Collections.Generic.List[string]
$hdr.Add("// Generated by tools/make_bangla.ps1 - do not edit by hand.")
$hdr.Add("// Bangla UI strings, pre-shaped by DirectWrite and baked to PNGs,")
$hdr.Add("// because raylib cannot shape Bengali conjuncts or reorder matras.")
$hdr.Add("// Edit the text in tools/bangla_strings.txt and re-run the script.")
$hdr.Add("#pragma once")
$hdr.Add("")
$hdr.Add("enum TextId {")
foreach ($r in $rows) { $hdr.Add("    TX_$($r[0]),") }
$hdr.Add("    TX_COUNT")
$hdr.Add("};")
$hdr.Add("")
$hdr.Add("static const char* TEXT_FILES[TX_COUNT] = {")
foreach ($r in $rows) { $hdr.Add("    `"assets/text/$($r[0]).png`",") }
$hdr.Add("};")

foreach ($r in $rows) {
    $d = Save-Text $r[0] $r[1] $r[2] $r[3]
    "{0,-14} {1,4}x{2,-4} {3}" -f $r[0], $d[0], $d[1], $r[1]
}

Set-Content -Path (Join-Path $root "src\textids.h") -Value ($hdr -join "`r`n") -Encoding UTF8
""
"wrote $($rows.Count) images to assets/text/ and src/textids.h"
