// ============================================================
//  Bangla UI text — pre-shaped PNGs, see text.cpp for why.
//  Ids come from src/textids.h, generated by tools/make_bangla.ps1.
// ============================================================
#pragma once
#include "raylib.h"

void  LoadUIText();
void  UnloadUIText();

// `h` is the height to draw at, in game pixels; width follows the aspect.
void  DrawUIText (int id, float x,  float y, float h, Color tint = WHITE);
void  DrawUITextC(int id, float cx, float y, float h, Color tint = WHITE);
float UITextW(int id, float h);
